model:
  node1: 128
  node2: 64

optimizer:
  lr: 0.001
  momentum: 0.9

train:
  epoch: 50
  batch_size: 64

test:
  batch_size: 64

mlflow:
  runname: 'optuna_sample'

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 42
    direction: maximize
    study_name: mnist
    storage: null
    n_trials: 20
    n_jobs: -1
