defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  sweeper:
    sampler:
      seed: 42
    direction: maximize
    study_name: sphere
    storage: null
    n_trials: 20
    n_jobs: 1

    search_space:
      x:
        type: float
        low: -5.5
        high: 5.5
        step: 0.5
      y:
        type: categorical
        choices: [-5, 0, 5]

x: 1
y: 1
