defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: motpe
# - override hydra/sweeper/sampler: random
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  sweeper:
    sampler:
      seed: 42
    direction: [minimize, minimize]
    study_name: multi-objective
    storage: null
    n_trials: 20
    n_jobs: 1

    search_space:
      x:
        type: float
        low: 0
        high: 5
        step: 0.1
      y:
        type: float
        low: 0
        high: 3
        step: 0.1

x: 1
y: 1
